### 
GET http://localhost:3000/auth/users


### 
POST http://localhost:3000/auth/users
Content-Type: application/json

{
  "username": "testuser",
  "password": "1234",
  "coins": 1000
}

###
PATCH http://localhost:3000/auth/users/3/coins
Content-Type: application/json

{
  "coins": 1500
}
